// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: proto/champs.proto

package champs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChampRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChampRequest) Reset() {
	*x = ChampRequest{}
	mi := &file_proto_champs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChampRequest) ProtoMessage() {}

func (x *ChampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_champs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChampRequest.ProtoReflect.Descriptor instead.
func (*ChampRequest) Descriptor() ([]byte, []int) {
	return file_proto_champs_proto_rawDescGZIP(), []int{0}
}

func (x *ChampRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChampResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rol  string `protobuf:"bytes,2,opt,name=rol,proto3" json:"rol,omitempty"`
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ChampResponse) Reset() {
	*x = ChampResponse{}
	mi := &file_proto_champs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChampResponse) ProtoMessage() {}

func (x *ChampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_champs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChampResponse.ProtoReflect.Descriptor instead.
func (*ChampResponse) Descriptor() ([]byte, []int) {
	return file_proto_champs_proto_rawDescGZIP(), []int{1}
}

func (x *ChampResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChampResponse) GetRol() string {
	if x != nil {
		return x.Rol
	}
	return ""
}

func (x *ChampResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type NewChampRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rol  string `protobuf:"bytes,2,opt,name=rol,proto3" json:"rol,omitempty"`
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *NewChampRequest) Reset() {
	*x = NewChampRequest{}
	mi := &file_proto_champs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewChampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChampRequest) ProtoMessage() {}

func (x *NewChampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_champs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChampRequest.ProtoReflect.Descriptor instead.
func (*NewChampRequest) Descriptor() ([]byte, []int) {
	return file_proto_champs_proto_rawDescGZIP(), []int{2}
}

func (x *NewChampRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewChampRequest) GetRol() string {
	if x != nil {
		return x.Rol
	}
	return ""
}

func (x *NewChampRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AddChampResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *AddChampResponse) Reset() {
	*x = AddChampResponse{}
	mi := &file_proto_champs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddChampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChampResponse) ProtoMessage() {}

func (x *AddChampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_champs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChampResponse.ProtoReflect.Descriptor instead.
func (*AddChampResponse) Descriptor() ([]byte, []int) {
	return file_proto_champs_proto_rawDescGZIP(), []int{3}
}

func (x *AddChampResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_champs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_champs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_champs_proto_rawDescGZIP(), []int{4}
}

type ChampTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ChampTypeRequest) Reset() {
	*x = ChampTypeRequest{}
	mi := &file_proto_champs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChampTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChampTypeRequest) ProtoMessage() {}

func (x *ChampTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_champs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChampTypeRequest.ProtoReflect.Descriptor instead.
func (*ChampTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_champs_proto_rawDescGZIP(), []int{5}
}

func (x *ChampTypeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_proto_champs_proto protoreflect.FileDescriptor

var file_proto_champs_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x68, 0x61, 0x6d, 0x70, 0x73, 0x22, 0x22, 0x0a, 0x0c,
	0x43, 0x68, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x49, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x72, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x4b, 0x0a, 0x0f, 0x4e,
	0x65, 0x77, 0x43, 0x68, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x72, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x28, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x43,
	0x68, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x26, 0x0a, 0x10, 0x43,
	0x68, 0x61, 0x6d, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x32, 0x8d, 0x02, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x6d, 0x70, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6d, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x2e, 0x63, 0x68, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x43, 0x68,
	0x61, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x63, 0x68, 0x61,
	0x6d, 0x70, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x36, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6d, 0x70, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x15, 0x2e, 0x63, 0x68, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6d, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x40, 0x0a, 0x09, 0x41, 0x64, 0x64,
	0x43, 0x68, 0x61, 0x6d, 0x70, 0x73, 0x12, 0x17, 0x2e, 0x63, 0x68, 0x61, 0x6d, 0x70, 0x73, 0x2e,
	0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x63, 0x68, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x68, 0x61, 0x6d,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x46, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x43, 0x68, 0x61, 0x6d, 0x70, 0x73, 0x62, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x2e, 0x63, 0x68, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6d, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x63, 0x68, 0x61, 0x6d, 0x70,
	0x73, 0x2e, 0x43, 0x68, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x1d, 0x5a, 0x1b, 0x63, 0x68, 0x61, 0x6d, 0x70, 0x73, 0x6c, 0x6f, 0x6c,
	0x2d, 0x67, 0x72, 0x63, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x63, 0x68, 0x61, 0x6d,
	0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_champs_proto_rawDescOnce sync.Once
	file_proto_champs_proto_rawDescData = file_proto_champs_proto_rawDesc
)

func file_proto_champs_proto_rawDescGZIP() []byte {
	file_proto_champs_proto_rawDescOnce.Do(func() {
		file_proto_champs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_champs_proto_rawDescData)
	})
	return file_proto_champs_proto_rawDescData
}

var file_proto_champs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_champs_proto_goTypes = []any{
	(*ChampRequest)(nil),     // 0: champs.ChampRequest
	(*ChampResponse)(nil),    // 1: champs.ChampResponse
	(*NewChampRequest)(nil),  // 2: champs.NewChampRequest
	(*AddChampResponse)(nil), // 3: champs.AddChampResponse
	(*Empty)(nil),            // 4: champs.Empty
	(*ChampTypeRequest)(nil), // 5: champs.ChampTypeRequest
}
var file_proto_champs_proto_depIdxs = []int32{
	0, // 0: champs.ChampService.GetChampInfo:input_type -> champs.ChampRequest
	4, // 1: champs.ChampService.GetChampList:input_type -> champs.Empty
	2, // 2: champs.ChampService.AddChamps:input_type -> champs.NewChampRequest
	5, // 3: champs.ChampService.GetChampsbyType:input_type -> champs.ChampTypeRequest
	1, // 4: champs.ChampService.GetChampInfo:output_type -> champs.ChampResponse
	1, // 5: champs.ChampService.GetChampList:output_type -> champs.ChampResponse
	3, // 6: champs.ChampService.AddChamps:output_type -> champs.AddChampResponse
	1, // 7: champs.ChampService.GetChampsbyType:output_type -> champs.ChampResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_champs_proto_init() }
func file_proto_champs_proto_init() {
	if File_proto_champs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_champs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_champs_proto_goTypes,
		DependencyIndexes: file_proto_champs_proto_depIdxs,
		MessageInfos:      file_proto_champs_proto_msgTypes,
	}.Build()
	File_proto_champs_proto = out.File
	file_proto_champs_proto_rawDesc = nil
	file_proto_champs_proto_goTypes = nil
	file_proto_champs_proto_depIdxs = nil
}
